name: elastic-cli

args:
  - verbosity:
      help: "Increase message verbosity"
      short: v
      multiple: true
  - quiet:
      help: "Silence all output"
      short: q
  - config:
      help: "Path to the configuration file"
      long: config
      takes_value: true
  - server:
      help: "Elasticsearch server name"
      long: server
      takes_value: true

subcommands:
  - search:
      about: "Search logs by the query"
      args:
        - index:
            help: "Elasticsearch index or index pattern"
            long: index
            short: i
            takes_value: true
        - query:
            help: "Query"
            long: query
            short: q
            takes_value: true
        - fields:
            help: "Fields"
            long: fields
            short: f
            takes_value: true
        - output:
            help: "Output format"
            long: output
            short: o
            takes_value: true
        - size:
            help: "Count of result for fetch"
            long: size
            default_value: "1000"
            takes_value: true
        - buffer:
            help: "Buffer size"
            long: buffer
            default_value: "1000"
            takes_value: true
        - pager:
            help: "Enable the pager for output"
            long: pager
  - config:
      about: "Configure"
      subcommands:
        - add:
            subcommands:
              - server:
                  args:
                    - name:
                        help: "Server name"
                        index: 1
                    - address:
                        help: "Server address"
                        long: address
                        takes_value: true
                    - index:
                        help: "Default index"
                        long: index
                        takes_value: true
                    - type:
                        help: "Type of server (elastic or kibana). Default: elastic"
                        long: type
                        takes_value: true
                    - username:
                        help: "Optional username for basic auth. If the '--password' option is not specified - the password will be asked"
                        long: username
                        takes_value: true
                    - password:
                        help: "Optional password for basic auth"
                        long: password
                        takes_value: true
        - update:
            subcommands:
              - server:
                  args:
                    - name:
                        help: "Server name"
                        index: 1
                    - address:
                        help: "Server address"
                        long: address
                        takes_value: true
                    - index:
                        help: "Default index"
                        long: index
                        takes_value: true
                    - type:
                        help: "Type of server (elastic or kibana)"
                        long: type
                        takes_value: true
                    - username:
                        help: "Optional username for basic auth. If the '--password' option is not specified - a password will be asked"
                        long: username
                        takes_value: true
                    - password:
                        help: "Optional password for basic auth"
                        long: password
                        takes_value: true
                    - ask-password:
                        help: "Force update the password. User name should be specified in the config file, or via the '--username' option"
                        long: ask-password
        - use:
            subcommands:
              - server:
                  args:
                    - name:
                        help: "Server name"
                        index: 1
        - show:
            about: "Show current configuration"